/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package springBootInitialDemo;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller
@SpringBootApplication
public class App {
	
	@RequestMapping("/")
	@ResponseBody
	public String helloWorld() {
		return "HELLO WORLD";
	}
	
	@RequestMapping("/{name}")
	@ResponseBody
	public String helloName(@PathVariable ("name") String name) {
		return "Hello, " + name;
	}
	
// https://www.baeldung.com/spring-requestmapping
// https://learning.postman.com/docs/sending-requests/managing-environments/

    public static void main(String[] args) {

        SpringApplication.run(App.class, args);
    }
}
